// <auto-generated />
using System;
using Avancerad.Net_Labb3_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avancerad.Net_Labb3_API.Migrations
{
    [DbContext(typeof(UserDbcontext))]
    [Migration("20260423115800_added-DTOs")]
    partial class addedDTOs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avancerad.Net_Labb3_API.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Koda och bygga system",
                            Title = "Programmering"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Snabba sportbilar",
                            Title = "Bilar"
                        });
                });

            modelBuilder.Entity("Avancerad.Net_Labb3_API.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserInterestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserInterestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            Url = "https://learn.microsoft.com",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            Url = "https://www.topgear.com",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 1,
                            Url = "https://stackoverflow.com",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Avancerad.Net_Labb3_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna@example.com",
                            Name = "Anna Andersson",
                            PhoneNumber = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bjorn@example.com",
                            Name = "Björn Borg",
                            PhoneNumber = "0709876543"
                        });
                });

            modelBuilder.Entity("Avancerad.Net_Labb3_API.Models.UserInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Avancerad.Net_Labb3_API.Models.Link", b =>
                {
                    b.HasOne("Avancerad.Net_Labb3_API.Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avancerad.Net_Labb3_API.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avancerad.Net_Labb3_API.Models.UserInterest", null)
                        .WithMany("Links")
                        .HasForeignKey("UserInterestId");

                    b.Navigation("Interest");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Avancerad.Net_Labb3_API.Models.UserInterest", b =>
                {
                    b.HasOne("Avancerad.Net_Labb3_API.Models.Interest", "Interests")
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avancerad.Net_Labb3_API.Models.User", "Users")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Avancerad.Net_Labb3_API.Models.Interest", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Avancerad.Net_Labb3_API.Models.User", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("Avancerad.Net_Labb3_API.Models.UserInterest", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
